server:
  port: 7998
  servlet:
    context-path: /api
spring:
  application:
    name: auth-service
springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
app:
  jwt:
    ttl: 3600
    access-token-ttl: 60
    secret: secret
    cookieName: jwt
    refresh-token-ttl: 120