//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.25 at 02:39:21 AM MSK 
//


package model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerNotifyStatus_QNAME = new QName("http://bpmEventManager.pecom.ru/model/notification", "CustomerNotifyStatus");
    private final static QName _CustomerNotifyStatusIsCancel_QNAME = new QName("http://bpmEventManager.pecom.ru/model/notification", "isCancel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerNotifyStatus }
     * 
     */
    public CustomerNotifyStatus createCustomerNotifyStatus() {
        return new CustomerNotifyStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerNotifyStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bpmEventManager.pecom.ru/model/notification", name = "CustomerNotifyStatus")
    public JAXBElement<CustomerNotifyStatus> createCustomerNotifyStatus(CustomerNotifyStatus value) {
        return new JAXBElement<CustomerNotifyStatus>(_CustomerNotifyStatus_QNAME, CustomerNotifyStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bpmEventManager.pecom.ru/model/notification", name = "isCancel", scope = CustomerNotifyStatus.class)
    public JAXBElement<Boolean> createCustomerNotifyStatusIsCancel(Boolean value) {
        return new JAXBElement<Boolean>(_CustomerNotifyStatusIsCancel_QNAME, Boolean.class, CustomerNotifyStatus.class, value);
    }

}
