//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.25 at 02:39:21 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bpmEventManager.pecom.ru/model/notification", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model;
